version = 0.1

[default.deploy.parameters]
stack_name = "free-tier-serverless-api"
resolve_s3 = true
s3_prefix = "free-tier-serverless-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
